### PR TITLE
Maintain: Appendix A and B

### PR DESCRIPTION
**Pull request by TAdev0**
#570

- - -
This change is [Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/623)

### CODE REVIEW

**Review by TAdev0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/623)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @enitrat)

___
*[`src/appendix-01-keywords.md` line 56 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/623#-NrBjKD2B_J-XAq-gq9m:-NrBq2YM0h-P7IzvVPu_:b-ri74c2) ([raw file](https://github.com/cairo-book/cairo-book/blob/710925a739cfb850bf5d942d09db5464f697e150/src/appendix-01-keywords.md#L56)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

not sure abt that
</blockquote></details>

about these loose keywords? or self?

I tried with self and super and i can define items with them
___
*[`src/appendix-01-keywords.md` line 92 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/623#-NrBjREx2QCvVrxHTRKh:-NrBqxIPDjnJmDy3_slv:b-xlcuk4) ([raw file](https://github.com/cairo-book/cairo-book/blob/710925a739cfb850bf5d942d09db5464f697e150/src/appendix-01-keywords.md#L92)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

duplicate?
</blockquote></details>

yes my fault

**Comment by TAdev0** [comment]
@enitrat  do you think built-in functions is relevant? For now , we should quote `assert` and `panic` corelib func  but there are plenty of others.  Should i add more? leave it like that? or remove examples with just a short explanation that we should not use the name of a corelib func for another item

**Review by enitrat — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/623)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @TAdev0)

___
*[`src/appendix-01-keywords.md` line 56 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/623#-NrBjKD2B_J-XAq-gq9m:-NrG2nBN6UR9IunJEbpk:b-5uycoc) ([raw file](https://github.com/cairo-book/cairo-book/blob/710925a739cfb850bf5d942d09db5464f697e150/src/appendix-01-keywords.md#L56)):*
<details><summary><i>Previously, TAdev0 (Tristan) wrote…</i></summary><blockquote>

about these loose keywords? or self?

I tried with self and super and i can define items with them
</blockquote></details>

self: the definition does not seem correct in the context of Cairo :thinking:  `self` would be the method subject

Also: what's "loose" for?

**Review by TAdev0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/623)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @enitrat)

___
*[`src/appendix-02-operators-and-symbols.md` line 104 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/623#-NrBjllJCODLPV3JXiGo:-NrWGOts5bP-fqo87AwC:bb7pcsz) ([raw file](https://github.com/cairo-book/cairo-book/blob/710925a739cfb850bf5d942d09db5464f697e150/src/appendix-02-operators-and-symbols.md#L104)):*
> ```Markdown
> | `#[starknet::contract]`              | Defines a Starknet smart contract |
> | `#[starknet::interface]`             | Defines a Starknet interface |
> | `#[starknet::component]`             | Defines a Starknet interface |
> ```

true
___
*[`src/appendix-02-operators-and-symbols.md` line 110 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/623#-NrBjwJcEJ7rsSbnS-pN:-NrWGlo--JHw_4Rlvwjk:b-7lcrwx) ([raw file](https://github.com/cairo-book/cairo-book/blob/710925a739cfb850bf5d942d09db5464f697e150/src/appendix-02-operators-and-symbols.md#L110)):*
> ```Markdown
> | `#[event]`                           | Defines an event in a smart contract |
> | `#[constructor]`                     | Defines the constructor in a smart contract |
> | `#[abi(embed_v0)]`                   | Defines an external function |
> ```

oh yeah, now idk why i wrote that
indeed it defines impls, not function. #[external(V0)] would be used to define a single public function, either outside impls block or with abi(per_item)
___
*[`src/appendix-02-operators-and-symbols.md` line 165 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/623#-NrBk9cQ2PKMD_0ijm-9:-NrWHnZs3AEiEveC2J1X:bdmyqut) ([raw file](https://github.com/cairo-book/cairo-book/blob/710925a739cfb850bf5d942d09db5464f697e150/src/appendix-02-operators-and-symbols.md#L165)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Braces ? I think
</blockquote></details>

both are correct
i also prefer braces, will change it

**Review by enitrat — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/623)* status: all files reviewed, 1 unresolved discussion (waiting on @TAdev0)

___
*[`src/appendix-02-operators-and-symbols.md` line 101 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/623#-NrBjh896G4s-dzp1a0c:-NrWR6UxBxE1Z2onzJ2G:b32wyo) ([raw file](https://github.com/cairo-book/cairo-book/blob/710925a739cfb850bf5d942d09db5464f697e150/src/appendix-02-operators-and-symbols.md#L101)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

is expected to panic? 

+ I think it's only used in the context of tests.
</blockquote></details>

up

**Review by enitrat — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/623)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TAdev0)

**Pull request merged**
