### PR TITLE
Maintain: Appendix D

### PR DESCRIPTION
**Pull request by TAdev0**
#570

- - -
This change is [Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/640)

### CODE REVIEW

**Comment by TAdev0** [comment]
@enitrat  same here, there are some traits and functions described but they concern contracts, i think we should remove them from the Cairo part appendix.

**Review by enitrat — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/640)* status: all files reviewed, 3 unresolved discussions (waiting on @TAdev0)

___
*[`src/appendix-04-common-types-and-traits-and-cairo-prelude.md` line 16 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/640#-NrlEGSV35qu9TWkJehH:-NrlEGSV35qu9TWkJehI:btro1gg) ([raw file](https://github.com/cairo-book/cairo-book/blob/df64c7475080dbbe2845cdf2c11d6ab1dee83771/src/appendix-04-common-types-and-traits-and-cairo-prelude.md#L16)):*
> ```Markdown
> operators, and utility functions. This includes: 
> 
> - Data types: felts, bools, arrays, dicts, etc.
> ```

better imo



_Suggestion:_
```Markdown
integers
```
___
*[`src/appendix-04-common-types-and-traits-and-cairo-prelude.md` line 17 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/640#-NrlER7w76kYOjqH8WW8:-NrlER7w76kYOjqH8WW9:bo5qk1q) ([raw file](https://github.com/cairo-book/cairo-book/blob/df64c7475080dbbe2845cdf2c11d6ab1dee83771/src/appendix-04-common-types-and-traits-and-cairo-prelude.md#L17)):*
> ```Markdown
> 
> - Data types: felts, bools, arrays, dicts, etc.
> - Traits: behaviors for arithmetic, comparison, serialization
> ```

missing word at the end "operations"
___
*[`src/appendix-04-common-types-and-traits-and-cairo-prelude.md` line 33 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/640#-NrlE_pbCQEjv_IavG-s:-NrlE_pbCQEjv_IavG-t:blokpui) ([raw file](https://github.com/cairo-book/cairo-book/blob/df64c7475080dbbe2845cdf2c11d6ab1dee83771/src/appendix-04-common-types-and-traits-and-cairo-prelude.md#L33)):*
> ```Markdown
> 
> - A general version, with a lot of traits that are made available, corresponding to `edition = "2023_01"`.
> - A restricted version, including the most essential traits needed for general cairo programming, corresponding to `edition = 2023_10`.
> ```

I think we should remove 2023_10 mentions and switch to 2023_11 - either you use the last, restricted edition, or the old, full one (preferably the former)

**Review by TAdev0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/640)* status: all files reviewed, 3 unresolved discussions (waiting on @enitrat)

___
*[`src/appendix-04-common-types-and-traits-and-cairo-prelude.md` line 16 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/640#-NrlEGSV35qu9TWkJehH:-NrpbjEC8IjLOicDfNEs:bb7pcsz) ([raw file](https://github.com/cairo-book/cairo-book/blob/df64c7475080dbbe2845cdf2c11d6ab1dee83771/src/appendix-04-common-types-and-traits-and-cairo-prelude.md#L16)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

better imo
</blockquote></details>

true
___
*[`src/appendix-04-common-types-and-traits-and-cairo-prelude.md` line 17 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/640#-NrlER7w76kYOjqH8WW8:-NrpbqV88ra0CBuP26Gj:bsv417u) ([raw file](https://github.com/cairo-book/cairo-book/blob/df64c7475080dbbe2845cdf2c11d6ab1dee83771/src/appendix-04-common-types-and-traits-and-cairo-prelude.md#L17)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

missing word at the end "operations"
</blockquote></details>

thank you.
___
*[`src/appendix-04-common-types-and-traits-and-cairo-prelude.md` line 33 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/640#-NrlE_pbCQEjv_IavG-s:-NrpdCv82gAGbdVjP-BC:bvnrpcm) ([raw file](https://github.com/cairo-book/cairo-book/blob/df64c7475080dbbe2845cdf2c11d6ab1dee83771/src/appendix-04-common-types-and-traits-and-cairo-prelude.md#L33)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I think we should remove 2023_10 mentions and switch to 2023_11 - either you use the last, restricted edition, or the old, full one (preferably the former)
</blockquote></details>

updated

**Review by enitrat — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/640)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @TAdev0)

___
*[`src/appendix-04-common-types-and-traits-and-cairo-prelude.md` line 33 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/640#-NrlE_pbCQEjv_IavG-s:-NrqAjoW16gdL-FklH7n:bblk2wr) ([raw file](https://github.com/cairo-book/cairo-book/blob/df64c7475080dbbe2845cdf2c11d6ab1dee83771/src/appendix-04-common-types-and-traits-and-cairo-prelude.md#L33)):*
<details><summary><i>Previously, TAdev0 (Tristan) wrote…</i></summary><blockquote>

updated
</blockquote></details>

2023_11

**Review by TAdev0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/640)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[`src/appendix-04-common-types-and-traits-and-cairo-prelude.md` line 33 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/640#-NrlE_pbCQEjv_IavG-s:-Nrqf7Bb-B5S6hu5ptij:bc1fqn7) ([raw file](https://github.com/cairo-book/cairo-book/blob/df64c7475080dbbe2845cdf2c11d6ab1dee83771/src/appendix-04-common-types-and-traits-and-cairo-prelude.md#L33)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

2023_11
</blockquote></details>

thanks.. my bad

**Comment by TAdev0** [comment]
@enitrat  should be ready for merge

**Review by enitrat — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/640)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TAdev0)

**Pull request merged**
