### PR TITLE
Advanced Cairo: Using arrays inside dicts

### PR DESCRIPTION
**Pull request by misicnenad**
Resolves https://github.com/cairo-book/cairo-book/issues/421

Disclaimer: 
I wrote this section with my current understanding of the underlying factors that make it necessary to work with arrays stored in dicts as described, so it's possible some of the explanations are misguided. If this is the case, I'd be more than grateful for any and all corrections.

- - -
This change is [Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/827)

### CODE REVIEW

**Review by enitrat — APPROVED** [review]
Great work 💯

**Comment by enitrat** [comment]
@misicnenad for future PRs can you avoid merging main with it's history to the feature branch? This creates conflicts when tracking contributions?

**Comment by enitrat** [comment]
also: you need to add a `//TAG: does_not_compile` line at the beginning of the cairo file that doesn't compile so that CI skips trying to compile it

**Comment by misicnenad** [comment]
> also: you need to add a `//TAG: does_not_compile` line at the beginning of the cairo file that doesn't compile so that CI skips trying to compile it

I actually added that, and then removed for reasons I do not remember. 

Will add it back.

**Comment by misicnenad** [comment]
> @misicnenad for future PRs can you avoid merging main with it's history to the feature branch? This creates conflicts when tracking contributions?

I just saw that my commit history is cluttered with unrelated commits. I must have messed something up when rebasing.

I just cleaned the history up, let me know if this is better.

**Comment by enitrat** [comment]
one last format error :)

**Review by enitrat — APPROVED** [review]

**Pull request merged**
