### PR TITLE
Maintain Chapter 8

### LINKED ISSUE #565: Maintain Chapter 8 Generic types
- [ ] this section should be renamed Generic types and Traits
- [ ] intro: `contractAddress` used as variable type example but never mentioned before because specific to starknet, maybe we should change it
- [ ] 8-2: rework last example

### PR DESCRIPTION
**Pull request by TAdev0**
Resolves #565

- - -
This change is [Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/581)

### CODE REVIEW

**Comment by TAdev0** [comment]
@enitrat  : 
- i annotated "# [preprocessor.last-changed]". in book.toml, i think we can even remove it. This is to remove the ''last commit .." on each page of the book
- for the last example in 8-2 i'm not really satisfied. before, there was some weird code, not in adequation with comments, and inlined in the .md file. (with the last no_listing unused). I used this no_listing and modified a few things. The problem is that i think i'm showing that we need to import a trait to define an impl for that trait in a scope.  But i guess this example should also higlight the opposite, ie importing an impl is mandatory in addition to the trait if the impl is defined elswhere. Tell me what you think.

**Comment by TAdev0** [comment]
also there is comments to add sections : 
```
<!-- ## Traits as parameters
...

<!-- TODO trait bound syntax -->

<!-- TODO multiple trait bounds -->

<!-- TODO: Using trait bounds to conditionally implement methods -->
```

I checked the rust book but it seems these features are not available for now with Cairo?

**Comment by enitrat** [comment]
I'm proposing to refactor this chapter entirely because I'm not satisfied with how things are first introduced. Things that I noticed are missing. Genericity is an "advanced" feature in every language, and thus readers might not be familiar with the concepts.
- Introduction to the chapter: what we're going to discuss - could be improved (cf rustbook)
- Introduction to generics data types: why would I make a function generic ? what do I gain from it
- Rename the chapter Generic Functions to Generic Data Types
- The `Wallet` example is far fetched - I think it was written like this to replicate the spirit of the rustbook with points but just less good

Apart from that the content of the first "Generic Functions" is good, but for the second section I think it should be reworked entirely. will think about it

**Comment by TAdev0** [comment]
@enitrat  yes i changed the name of the section from Generic Functions to Generic Data Types in Summary, but i just noticed indeed this needs to be changed in the first title of the section as well.

Will rework intros
I personally liked the wallet exemple ^^

**Comment by enitrat** [comment]
> I personally liked the wallet exemple ^^

ok, let's keep it for now

**Comment by TAdev0** [comment]
@enitrat  tell me what you want to improve more. I feel like the generic concept is clearly introduced, but i read it many times now so i might be biased

**Comment by enitrat** [comment]
I think we should hand-guide the user and make him self-realize how he can factor his code to avoid code duplication inside functions, and duplications OF functions. I really liked how they've done it in the introduction of the Generic Data Types in the rust book.

> generic functions'' seems correct for the first section of the chapter
The section is not just about functions, but also structs, enums and methods!

**Comment by TAdev0** [comment]
Ok sorry quiproquo again, I already changed the name of the section. 
I was talking about the first "subsection" of the first section of the chapter, which is "generic functions" and should stay like that. Then we have constrains subsection, anonymous subsection, struct, enum..

But yeah, the name of the section in the summary (the menu on the left of the book) was wrong. 

Ok I will take inspiration in the rust book to enhance the introduction and showcase what you mentioned

**Review by enitrat — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 2 of 5 files at r2, 2 of 2 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/581)* status: all files reviewed, 15 unresolved discussions (waiting on @TAdev0)

___
*[`book.toml` line 19 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHQbel9L9c1-qnPH0E:-NqHQbemE8ogPq1aGZ3s:b-6f27we) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/book.toml#L19)):*
> ```TOML
> # [preprocessor.last-changed]
> # command = "mdbook-last-changed"
> # renderer = ["html"]
> ```

I agree to delete them entirely



_Code quote:_
```TOML
# [preprocessor.last-changed]
# command = "mdbook-last-changed"
# renderer = ["html"]
```
___
*[`listings/ch08-generic-types-and-traits/no_listing_01_missing_tdrop/src/lib.cairo` line 2 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHQj2S3qiIxFVjLQPm:-NqHQj2S3qiIxFVjLQPn:b-zhxnaa) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/listings/ch08-generic-types-and-traits/no_listing_01_missing_tdrop/src/lib.cairo#L2)):*
> ```Cairo
> //TAG: does_not_compile
> // ANCHOR: generic
> ```

q: what's the tag for? Since the entire content are in tags
___
*[`listings/ch08-generic-types-and-traits/no_listing_03_missing_tcopy/src/lib.cairo` line 2 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHQpZR1xtq1tgVUKk9:-NqHQpZR1xtq1tgVUKkA:b-krsqec) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/listings/ch08-generic-types-and-traits/no_listing_03_missing_tcopy/src/lib.cairo#L2)):*
> ```Cairo
> //TAG: does_not_compile
> //ANCHOR: missing-tcopy
> ```

same Q
___
*[`listings/ch08-generic-types-and-traits/no_listing_17_generic_traits/src/lib.cairo` line 2 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHW0fMAdxj2-MFgRHd:-NqHW0fMAdxj2-MFgRHe:bat3zjq) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/listings/ch08-generic-types-and-traits/no_listing_17_generic_traits/src/lib.cairo#L2)):*
> ```Cairo
> #[derive(Copy, Drop)]
> struct Rectangle {
> ```

move to `rectangle` module
___
*[`listings/ch08-generic-types-and-traits/no_listing_17_generic_traits/src/lib.cairo` line 8 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHW1sBBocb47fRnx9x:-NqHW1sBBocb47fRnx9y:b-9w9jcv) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/listings/ch08-generic-types-and-traits/no_listing_17_generic_traits/src/lib.cairo#L8)):*
> ```Cairo
> 
> #[derive(Copy, Drop)]
> struct Circle {
> ```

move to `circle` module
___
*[`listings/ch08-generic-types-and-traits/no_listing_17_generic_traits/src/lib.cairo` line 12 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHVzQa48nqwj5xGUQT:-NqHVzQa48nqwj5xGUQU:b-oq7f1q) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/listings/ch08-generic-types-and-traits/no_listing_17_generic_traits/src/lib.cairo#L12)):*
> ```Cairo
> }
> 
> mod geometry {
> ```

rename rectangle
___
*[`listings/ch08-generic-types-and-traits/no_listing_17_generic_traits/src/lib.cairo` line 16 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHVtHi2BWc8rXrAltJ:-NqHVtHi2BWc8rXrAltK:b-jk1699) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/listings/ch08-generic-types-and-traits/no_listing_17_generic_traits/src/lib.cairo#L16)):*
> ```Cairo
> 
>     // Here T is an alias type which will be provided during implementation
>     pub(crate) trait ShapeGeometry<T> {
> ```

can you move this trait outside of the `geometry` module and make it `pub`
___
*[`src/ch08-00-generic-types-and-traits.md` line 7 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHWQj6EDEK3aP4ZGtw:-NqHWQj6EDEK3aP4ZGtx:undefined) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/src/ch08-00-generic-types-and-traits.md#L7)):*
> ```Markdown
> Functions can take parameters of some generic type, instead of a concrete type like `u32` or `bool`, in the same way a function takes parameters with unknown values to run the same code on multiple concrete values. In fact, we’ve already used generics in [Chapter 6](ch06-01-enums.md) with `Option<T>`.
> 
> In this chapter, you’ll explore how to define your own types, functions, and methods with generics. You will also learn how to use generic types in struct, enum and definitions.
> ```





_Suggestion:_
```Markdown
and traits with generics
```
___
*[`src/ch08-00-generic-types-and-traits.md` line 7 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHWYyXEOCPG4oKZ4Kj:-NqHWYyXEOCPG4oKZ4Kk:boduxp8) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/src/ch08-00-generic-types-and-traits.md#L7)):*
> ```Markdown
> Functions can take parameters of some generic type, instead of a concrete type like `u32` or `bool`, in the same way a function takes parameters with unknown values to run the same code on multiple concrete values. In fact, we’ve already used generics in [Chapter 6](ch06-01-enums.md) with `Option<T>`.
> 
> In this chapter, you’ll explore how to define your own types, functions, and methods with generics. You will also learn how to use generic types in struct, enum and definitions.
> ```

redundant with "own types"?



_Code quote:_
```Markdown
You will also learn how to use generic types in struct, enum and definitions.
```
___
*[`src/ch08-00-generic-types-and-traits.md` line 9 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHX1sk3ZbEDdUxioWM:-NqHX1sk3ZbEDdUxioWN:bj1tfz6) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/src/ch08-00-generic-types-and-traits.md#L9)):*
> ```Markdown
> In this chapter, you’ll explore how to define your own types, functions, and methods with generics. You will also learn how to use generic types in struct, enum and definitions.
> 
> Generics allow us to replace specific types with a placeholder that represents multiple types to remove code duplication. However, the compiler creates a new definition for each concrete type that replaces a generic type, reducing development time for the programmer, but code duplication at compile level still exists. This may be of importance if you are writing Starknet contracts and using a generic for multiple types which will cause contract size to increment.
> ```

However is not the right word here, it's not an opposition



_Suggestion:_
```Markdown
Upon compilation,
```
___
*[`src/ch08-02-traits-in-cairo.md` line 25 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHRyo1DHFDTMv_LBcA:-NqHRyo2DPp6-FN-9o2l:b-pn784f) ([raw file](https://github.com/cairo-book/cairo-book/blob/b72de38daebd6df3fe43f5bc2356bd4f70fb9b94/src/ch08-02-traits-in-cairo.md#L25)):*
> ```Markdown
> Here, we declare a trait using the trait keyword and then the trait’s name, which is `Summary` in this case.
> 
> 
> ```

this was meant to be kept but uncommented



_Code quote:_
```Markdown
<!-- We’ve also declared the trait as pub so that crates depending on this crate can make use of this trait too, as we’ll see in a few examples.  -->
```
___
*[`src/ch08-02-traits-in-cairo.md` line 29 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHS3BHCrUsMc-jGzQE:-NqHS3BHCrUsMc-jGzQF:undefined) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/src/ch08-02-traits-in-cairo.md#L29)):*
> ```Markdown
> As the trait is not generic, the `self` parameter is not generic either and is of type `@NewsArticle`. This means that the `summarize` method can only be called on instances of `NewsArticle`.
> 
> Now, consider that we want to make a media aggregator library crate named _aggregator_ that can display summaries of data that might be stored in a `NewsArticle` or `Tweet` instance. To do this, we need a summary from each type, and we’ll request that summary by calling a summarize method on an instance. By defining the `Summary` trait on generic type `T`, we can implement the `summarize` method on any type we want to be able to summarize.
> ```





_Suggestion:_
```Markdown
on an instance of that type.
```
___
*[`src/ch08-02-traits-in-cairo.md` line 44 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHSRQM0tTi_saGjZa4:-NqHSRQM0tTi_saGjZa5:b7rshp0) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/src/ch08-02-traits-in-cairo.md#L44)):*
> ```Markdown
> 
> Now that we’ve defined the desired signatures of the `Summary` trait’s methods,
> we can implement it on the types in our media aggregator. The next code snippet shows
> ```

Ideally refer to a named listing here



_Code quote:_
```Markdown
The next code snippet
```
___
*[`src/ch08-02-traits-in-cairo.md` line 57 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHT3fY0xgvfsIrB-Bo:-NqHT3fY0xgvfsIrB-Bp:brrd279) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/src/ch08-02-traits-in-cairo.md#L57)):*
> ```Markdown
> Implementing a trait on a type is similar to implementing regular methods. The
> difference is that after `impl`, we put a name for the implementation,
> then use the `of` keyword, and then specify the name of the trait we are writing the implementation for.
> ```

Hm actually this doesn't make sense in cairo, because we also do this for methods. 
e.g if you want to define methods on a person you would write

```
#[generate_trait]
impl HumanMethods of Human{
  fn get_name (self: @Person) -> felt252 {self.name}
}
```

and if you write a trait that defines a common interface for all mammals you would write
```
trait Mammal<T> {
 fn get_height() -> u32;
}

impl MammalHuman of Mammal<Human>{
   fn get_height(self: @Human) -> u32 {self.height}
}

```

The only difference is that for the type's "method" , we use a `#[generate_trait]`, not generic argument, and can define `self` to be any kind, while for the "trait implementation" we implement an explicit trait taking a generic arg.

I think this deserves more reflection on how to properly approach and explain methods and trait impls. Could you open a new issue for that?



_Code quote:_
```Markdown
Implementing a trait on a type is similar to implementing regular methods. The
difference is that after `impl`, we put a name for the implementation,
then use the `of` keyword, and then specify the name of the trait we are writing the implementation for.
```
___
*[`src/ch08-02-traits-in-cairo.md` line 114 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHV18j5eO-b5ZmSIP_:-NqHV18j5eO-b5ZmSIPa:b6y484y) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/src/ch08-02-traits-in-cairo.md#L114)):*
> ```Markdown
> 
> 
> ## Implementing a trait, without writing its declaration
> ```

Regarding the comment above: I think this should be removed from this chapter and only talked about as a method implementation. Can you also add it in the issue description?



_Code quote:_
```Markdown
## Implementing a trait, without writing its declaration
```

**Review by TAdev0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/581)* status: 7 of 21 files reviewed, 15 unresolved discussions (waiting on @enitrat and @TAdev0)

___
*[`book.toml` line 19 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHQbel9L9c1-qnPH0E:-NqHy1JL82Y5xft8nW-o:bb7f2mf) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/book.toml#L19)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I agree to delete them entirely
</blockquote></details>

done
___
*[`listings/ch08-generic-types-and-traits/no_listing_01_missing_tdrop/src/lib.cairo` line 2 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHQj2S3qiIxFVjLQPm:-NqHy7W4CGGJ0s-QBGwW:b-rlmjd8) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/listings/ch08-generic-types-and-traits/no_listing_01_missing_tdrop/src/lib.cairo#L2)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

q: what's the tag for? Since the entire content are in tags
</blockquote></details>

to avoid printing `//TAG: does_not_compile` in the snippet
___
*[`listings/ch08-generic-types-and-traits/no_listing_03_missing_tcopy/src/lib.cairo` line 2 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHQpZR1xtq1tgVUKk9:-NqHyAFp8IQOFR_-acgT:b-rlmjd8) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/listings/ch08-generic-types-and-traits/no_listing_03_missing_tcopy/src/lib.cairo#L2)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

same Q
</blockquote></details>

to avoid printing `//TAG: does_not_compile` in the snippet
___
*[`listings/ch08-generic-types-and-traits/no_listing_17_generic_traits/src/lib.cairo` line 2 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHW0fMAdxj2-MFgRHd:-NqI0UIj7kjVGx2sQCG3:bb7f2mf) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/listings/ch08-generic-types-and-traits/no_listing_17_generic_traits/src/lib.cairo#L2)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

move to `rectangle` module
</blockquote></details>

done
___
*[`listings/ch08-generic-types-and-traits/no_listing_17_generic_traits/src/lib.cairo` line 8 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHW1sBBocb47fRnx9x:-NqI34BkAXjxHlr9xhLq:bb7f2mf) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/listings/ch08-generic-types-and-traits/no_listing_17_generic_traits/src/lib.cairo#L8)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

move to `circle` module
</blockquote></details>

done
___
*[`listings/ch08-generic-types-and-traits/no_listing_17_generic_traits/src/lib.cairo` line 12 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHVzQa48nqwj5xGUQT:-NqI3NhO0FwnP-Ov_wiA:bb7f2mf) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/listings/ch08-generic-types-and-traits/no_listing_17_generic_traits/src/lib.cairo#L12)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

rename rectangle
</blockquote></details>

done
___
*[`listings/ch08-generic-types-and-traits/no_listing_17_generic_traits/src/lib.cairo` line 16 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHVtHi2BWc8rXrAltJ:-NqI3cD-25RL-V96r8vs:bb7f2mf) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/listings/ch08-generic-types-and-traits/no_listing_17_generic_traits/src/lib.cairo#L16)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

can you move this trait outside of the `geometry` module and make it `pub`
</blockquote></details>

done
___
*[`src/ch08-00-generic-types-and-traits.md` line 7 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHWQj6EDEK3aP4ZGtw:-NqI4df-1GvtkTRQ-Mkb:bb7lbs2) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/src/ch08-00-generic-types-and-traits.md#L7)):*
> ```Markdown
> Functions can take parameters of some generic type, instead of a concrete type like `u32` or `bool`, in the same way a function takes parameters with unknown values to run the same code on multiple concrete values. In fact, we’ve already used generics in [Chapter 6](ch06-01-enums.md) with `Option<T>`.
> 
> In this chapter, you’ll explore how to define your own types, functions, and methods with generics. You will also learn how to use generic types in struct, enum and definitions.
> ```

nice
___
*[`src/ch08-00-generic-types-and-traits.md` line 7 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHWYyXEOCPG4oKZ4Kj:-NqI5SU236ccvaF2f4Nv:bb7pcsz) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/src/ch08-00-generic-types-and-traits.md#L7)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

redundant with "own types"?
</blockquote></details>

true
___
*[`src/ch08-00-generic-types-and-traits.md` line 9 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHX1sk3ZbEDdUxioWM:-NqI5_sm83_NRPiprG3i:bosc5n) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/src/ch08-00-generic-types-and-traits.md#L9)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

However is not the right word here, it's not an opposition
</blockquote></details>

yeah i felt uncomfortable with this word
it kind of fits with the end of the sentence " .. code duplication at compile level still exists" but not the beginning. Your proposition is way better
___
*[`src/ch08-02-traits-in-cairo.md` line 25 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHRyo1DHFDTMv_LBcA:-NqIHBQpDbiqp1hjHp0U:b-osxlqv) ([raw file](https://github.com/cairo-book/cairo-book/blob/b72de38daebd6df3fe43f5bc2356bd4f70fb9b94/src/ch08-02-traits-in-cairo.md#L25)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

this was meant to be kept but uncommented
</blockquote></details>

oh yes i removed it because i also removed the ''pub'' attribute for the first example. just added it again and modified the snippet to make it pub again
___
*[`src/ch08-02-traits-in-cairo.md` line 29 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHS3BHCrUsMc-jGzQE:-NqIHTVt6oJzxcuETWUL:bb7f2mf) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/src/ch08-02-traits-in-cairo.md#L29)):*
> ```Markdown
> As the trait is not generic, the `self` parameter is not generic either and is of type `@NewsArticle`. This means that the `summarize` method can only be called on instances of `NewsArticle`.
> 
> Now, consider that we want to make a media aggregator library crate named _aggregator_ that can display summaries of data that might be stored in a `NewsArticle` or `Tweet` instance. To do this, we need a summary from each type, and we’ll request that summary by calling a summarize method on an instance. By defining the `Summary` trait on generic type `T`, we can implement the `summarize` method on any type we want to be able to summarize.
> ```

done
___
*[`src/ch08-02-traits-in-cairo.md` line 44 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHSRQM0tTi_saGjZa4:-NqIHbDbEBfd95EltbPT:bcti9ws) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/src/ch08-02-traits-in-cairo.md#L44)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Ideally refer to a named listing here
</blockquote></details>

ok, there is no reference to listings in this whole chapter. would be probably more weird to add just one "Listing 8-1" in the middle of the 2nd section?
I can try something else, and then after maintenance make a PR to standardize the whole book for quoted listings
___
*[`src/ch08-02-traits-in-cairo.md` line 57 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHT3fY0xgvfsIrB-Bo:-NqIJRxkB24KJIvjkHwt:bsq64f6) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/src/ch08-02-traits-in-cairo.md#L57)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Hm actually this doesn't make sense in cairo, because we also do this for methods. 
e.g if you want to define methods on a person you would write

```
#[generate_trait]
impl HumanMethods of Human{
  fn get_name (self: @Person) -> felt252 {self.name}
}
```

and if you write a trait that defines a common interface for all mammals you would write
```
trait Mammal<T> {
 fn get_height() -> u32;
}

impl MammalHuman of Mammal<Human>{
   fn get_height(self: @Human) -> u32 {self.height}
}

```

The only difference is that for the type's "method" , we use a `#[generate_trait]`, not generic argument, and can define `self` to be any kind, while for the "trait implementation" we implement an explicit trait taking a generic arg.

I think this deserves more reflection on how to properly approach and explain methods and trait impls. Could you open a new issue for that?
</blockquote></details>

interesting, i understand how it is wrongly explained.
Sure.
___
*[`src/ch08-02-traits-in-cairo.md` line 114 at r5](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqHV18j5eO-b5ZmSIP_:-NqILqfyAxQtnh06l-2S:b2nign6) ([raw file](https://github.com/cairo-book/cairo-book/blob/7ba0703882ebab284047f9a04114fedea9b679c8/src/ch08-02-traits-in-cairo.md#L114)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Regarding the comment above: I think this should be removed from this chapter and only talked about as a method implementation. Can you also add it in the issue description?
</blockquote></details>

yes

**Review by enitrat — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/581)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @TAdev0)

___
*[`src/ch08-02-traits-in-cairo.md` line 63 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqJkzUT7qqmrMNLDzfq:-NqJkzUU7zho8rTStpx9:b-q35uz4) ([raw file](https://github.com/cairo-book/cairo-book/blob/6d5b0f9d0cc1fe057fd7e55dd0ae55672c4a9717/src/ch08-02-traits-in-cairo.md#L63)):*
> ```Markdown
> If the implementation is for a generic type, we place the generic type name in the angle brackets after the trait name.
> 
> Note that we don't need to define the implementation as `pub` if the trait it implements is `pub` itself. Defining an implementation as `pub` only allows to access its path externally.
> ```

Hmmm, yes, but it's very ambiguous here, it's not clear what is referred to.

- If you want to access the impl item (and its methods) itself, you can't (not visible) - as you properly noted
- If you want to call the trait's method, you can if the trait is public
- If the impl is not defined in the same place than the trait, I think this could cause issues.

Try this:
```rust
mod internal {
    pub trait MyTrait {
        fn foo();
    }
}

mod internal2 {
    pub impl MyImpl of super::internal::MyTrait {
        fn foo() {
            println!("foo");
        }
    }
}

mod internal3 {
    use super::internal;
    // use super::internal2::MyImpl; the implementation must be visible from the place where the trait is used
    fn main() {
        // impl not public
        internal2::MyImpl::foo();
        // trait not public
        internal::MyTrait::foo();
    }
}
```

For the trait method to be called, there must be a visible implementation of that trait in the scope where it's called, I think we should fix this ambiguity



_Suggestion:_
```Markdown
Note that for the trait method to be accessible, there must be an implementation of that trait visible from the scope where the method is called. If the trait is `pub` and the implementation is not, and the implementation is not visible in the scope where the trait method is called, this will cause a compilation error.
```

**Review by TAdev0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/581)* status: 19 of 21 files reviewed, 1 unresolved discussion (waiting on @enitrat)

___
*[`src/ch08-02-traits-in-cairo.md` line 63 at r6](https://reviewable.io/reviews/cairo-book/cairo-book/581#-NqJkzUT7qqmrMNLDzfq:-NqN9C2N0g9xT8xt4bRX:b87w9z2) ([raw file](https://github.com/cairo-book/cairo-book/blob/6d5b0f9d0cc1fe057fd7e55dd0ae55672c4a9717/src/ch08-02-traits-in-cairo.md#L63)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Hmmm, yes, but it's very ambiguous here, it's not clear what is referred to.

- If you want to access the impl item (and its methods) itself, you can't (not visible) - as you properly noted
- If you want to call the trait's method, you can if the trait is public
- If the impl is not defined in the same place than the trait, I think this could cause issues.

Try this:
```rust
mod internal {
    pub trait MyTrait {
        fn foo();
    }
}

mod internal2 {
    pub impl MyImpl of super::internal::MyTrait {
        fn foo() {
            println!("foo");
        }
    }
}

mod internal3 {
    use super::internal;
    // use super::internal2::MyImpl; the implementation must be visible from the place where the trait is used
    fn main() {
        // impl not public
        internal2::MyImpl::foo();
        // trait not public
        internal::MyTrait::foo();
    }
}
```

For the trait method to be called, there must be a visible implementation of that trait in the scope where it's called, I think we should fix this ambiguity
</blockquote></details>

great i learned something its much more clear with this example. Your suggestion is perfect to explain it

**Review by enitrat — COMMENTED** [review]
> Reviewed 1 of 14 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/581)* status: all files reviewed, 1 unresolved discussion (waiting on @TAdev0)

**Review by enitrat — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/581#-:-NqTBt5fErCL7NEfD7Ra:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TAdev0)

**Comment by julio4** [comment]
>     * i annotated "# [preprocessor.last-changed]". in book.toml, i think we can even remove it. This is to remove the ''last commit .." on each page of the book

Any reasons why this was an issue? I added it because it was useful (for me atleast) as there are no versioning of the book, so I'm curious to know why it was troublesome.

**Comment by enitrat** [comment]
@julio4 I think it was not working properly

**Pull request merged**
