### PR TITLE
delete usize type

### PR DESCRIPTION
**Pull request by suiwater**
refer to:https://docs.cairo-lang.org/language_constructs/integer-types.html

- - -
This change is [Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/673)

### CODE REVIEW

**Comment by enitrat** [comment]
yes let's keep it

**Comment by suiwater** [comment]
https://github.com/cairo-book/cairo-book/blob/bdb74f2bf4c0b450ba3e0b08fc1059d4a236ac87/listings/ch08-generic-types-and-traits/listing_impl_aliases/src/lib.cairo#L17
https://doc.rust-lang.org/book/ch03-02-data-types.html
in rust:usize types depend on the architecture of the computer your program is running on.
usize  is just an alias to u32

**Comment by suiwater** [comment]
@enitrat

**Comment by enitrat** [comment]
yes, I know

**Pull request closed without merging**
