### PR TITLE
Minor Typo fix in Chapter 10.3

### PR DESCRIPTION
**Pull request by mananbordia**
### Summary

- Making this amazing resource more typo free.

Replaced term `updateted` with `updated`

- - -
This change is [Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/486)

### CODE REVIEW

**Review by enitrat — APPROVED** [review]
hey is this draft or ready?

**Comment by mananbordia** [comment]
Yes @enitrat, this is still in draft. 
I'm planning of making all the changes in single PR instead of raising multiple PRs.

**Comment by enitrat** [comment]
Great, I'll leave it open then :)

**Comment by mananbordia** [comment]
@enitrat I wasn't able to find more typos within the book. Can we ship this ?

**Comment by enitrat** [comment]
🚀

**Pull request merged**
