### PR TITLE
fix small Typo

### PR DESCRIPTION
**Pull request by hardiktheprogrammer**
- fix small issue  in documentation

- - -
This change is [Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/484)

### CODE REVIEW

**Comment by enitrat** [comment]
is this spam or is this serious?

**Comment by hardiktheprogrammer** [comment]
> is this spam or is this serious?

no, i just make small changes

**Comment by enitrat** [comment]
what did you change ? Besides formatting in bold a word?

**Comment by hardiktheprogrammer** [comment]
> what did you change ? Besides formatting in bold a word?

yeah  just formatting bold a words

**Comment by enitrat** [comment]
but why? This wasn't an issue

**Comment by hardiktheprogrammer** [comment]
> but why? This wasn't an issue

yeah I know but it's just a small  change I hope you merge this, next time focusing on issues

**Comment by enitrat** [comment]
Sorry, I won't merge

**Pull request closed without merging**
