### PR TITLE
Chore: bumped scarb and starknet version to v2.7.0

### PR DESCRIPTION
**Pull request by supreme2580**
I have found and replaced all starknet dependencies and scarb version of 2.7.0-rc.3 to 2.7.0

Closes: https://github.com/cairo-book/cairo-book/issues/900

- - -
This change is [Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/901)

### CODE REVIEW

**Comment by enitrat** [comment]
CI fails because scarb release is not published yet, should be in the next hour or so

**Comment by supreme2580** [comment]
Oh okay thank you very much

**Comment by supreme2580** [comment]
Hi @enitrat generating cairo listings is failing, what could be the issue?

**Comment by enitrat** [comment]
fixed that

**Review by enitrat — APPROVED** [review]

**Comment by supreme2580** [comment]
@enitrat the build is now passing🚀🚀🚀

**Pull request merged**
