### PR TITLE
fixed size array type

### LINKED ISSUE #596: feat : 2.6.0
- [x] if - let expression
- [x] while let support.
- [x] assert_lt!, assert_le!, assert_ge!, assert_gt! in tests
- [x] underscore pattern in match on tuples (ie you can do `_ =>` instead of (_ , _) =>`
- [x] Support for complex consts (Non-Zero, struct, enum, fixed size arrays).
- [x] Change all ` loop { arr.pop_front ...} ` loops to `while let Option::Some` loops - except the ones used for the `loop` keyword explicitly
- [x] Const array type https://doc.rust-lang.org/book/ch03-02-data-types.html#the-array-type

### PR DESCRIPTION
**Pull request by TAdev0**
Closes #596 

@enitrat  i didn't create a dedicated file for the snippets because they are one line and it wont compile for now. Do you prefer to put these variable declarations in a main function with a TAG does_not_compile?

- - -
This change is [Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/709)

### CODE REVIEW

**Comment by enitrat** [comment]
@TAdev0 why do they not compile?

**Comment by TAdev0** [comment]
@enitrat because the implementation of Drop is not yet a in a release

**Comment by enitrat** [comment]
ok, then let's keep this open until it's properly supported

**Comment by misicnenad** [comment]
@TAdev0 can this PR be reopened?
Just found out about const arrays, and I wish I knew about them sooner

**Pull request closed without merging**
