### PR TITLE
chore: remove formal verification chapter

### PR DESCRIPTION
**Pull request by TAdev0**
This change is [Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/956)

### CODE REVIEW

**Comment by enitrat** [comment]
I would remove this as non of these are usable in production

**Comment by TAdev0** [comment]
remove the references or the whole chapter?

could be nice to leave the chapter with the short explanation? dont know actually

**Comment by enitrat** [comment]
I don't see the point of talking about formal verification if it's not something you can leverage for your contracts security. If there's any tool easily usable, why not, but I don't think it's the case today

**Comment by TAdev0** [comment]
@enitrat  ready to merge

**Pull request merged**
