### PR TITLE
Maintain Chapter 6-1: Enum

### LINKED ISSUE #562: Maintain Chapter 6-1 Enums
- [x] lack of example for instantiation of enum with associated data
- [ ] Rework examples for Option enum
- [x] Maybe add a short introduction to the Result enum?

### PR DESCRIPTION
**Pull request by TAdev0**
Resolves #562 

@enitrat  about the last `find_value` example, there was a note to change it.
I think it could be nice to keep it:
- nice to have a little more advanced example at this moment
- this example combines : snapshot and array, while loop which are all previously introduced notions

But removing the test could be a good idea : 
- it includes all non introduced syntax about tests (cfg(test), etc)
- it includes match construct and this is the subject of the next session

- - -
This change is [Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/589)

### CODE REVIEW

**Review by TAdev0 — COMMENTED** [review]
ok!

I updated the functions, but i have a warning for the recursive one, `Unhandled \`#\[must\_use\]\` type \`core::option::Option::<core::integer::u32>\`

But it compiles correctly. Should i use the return value of the function, although i don't need it?

> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/589#-:-NqTWhck5A1oc5b0DHTr:b-fb5zid)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @TAdev0)

**Review by enitrat — CHANGES_REQUESTED** [review]
I was curious about this `while` loop so I ran gas estimations. Doesn't matter much, but here's the result:

```rust
fn rec(mut arr: Span<u8>, value: u8, index: u32) -> Option<usize> {
    match arr.pop_front() {
        Option::Some(x) => { if *x == value {
            return Option::Some(index);
        } },
        Option::None => { return Option::None; }
    }

    return rec(arr, value, index + 1);
}

// using array indexes
fn rec2(arr: Span<u8>, value: u8, index: u32) -> Option<usize> {
    if arr.len() == index {
        return Option::None;
    }

    if *arr[index] == value {
        return Option::Some(index);
    }

    return rec2(arr, value, index + 1);
}


fn loop1(mut arr: Span<u8>, value: u8) -> Option<usize> {
    let mut index = 0;
    let mut found: Option<usize> = Option::None;

    while true {
        match arr.pop_front() {
            Option::Some(index_value) => if (*index_value == value) {
                found = Option::Some(index)
            },
            Option::None => { break; },
        }
        index += 1;
    };

    found
}

// using loop {} syntax
fn loop2(mut arr: Span<u8>, value: u8) -> Option<usize> {
    let mut index = 0;
    loop {
        match arr.pop_front() {
            Option::Some(array_value) => if (*array_value == value) {
                break Option::Some(index);
            },
            Option::None => { break Option::None; },
        }
        index += 1;
    }
}

#[cfg(test)]
mod tests {
    use super::{rec, rec2};

    #[test]
    // 563920 gas
    fn test_rec() {
        let arr = array![1, 2, 3, 4, 5].span();
        assert_eq!(rec(arr, 3, 0), Option::Some(2));
    }

    #[test]
    // 568330
    fn test_rec2() {
        let arr = array![1, 2, 3, 4, 5].span();
        assert_eq!(rec2(arr, 3, 0), Option::Some(2));
    }

    #[test]
    // 586540
    fn test_loop1() {
        let arr = array![1, 2, 3, 4, 5].span();
        assert_eq!(super::loop1(arr, 3), Option::Some(2));
    }

    #[test]
    // 566120
    fn test_loop2() {
        let arr = array![1, 2, 3, 4, 5].span();
        assert_eq!(super::loop2(arr, 3), Option::Some(2));
    }
}

```

> but i have a warning for the recursive one, `Unhandled \`#\[must\_use\]\` type \`core::option::Option::core::integer::u32\`

not sure what this is - but i'd advise using my version instead (which has no extra stuff)

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/589#-:-NqTxSQ-7HQkEu--K2Sr:b-pl2r39)* status: all files reviewed, 3 unresolved discussions (waiting on @TAdev0)

___
*[`listings/ch06-enums-and-pattern-matching/no_listing_03_enum_option/src/lib.cairo` line 5 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/589#-NqTv6hlBdR12UNPowDE:-NqTv6hlBdR12UNPowDF:undefined) ([raw file](https://github.com/cairo-book/cairo-book/blob/bb2551a613764ae928ccc40417fd1003b03738de/listings/ch06-enums-and-pattern-matching/no_listing_03_enum_option/src/lib.cairo#L5)):*
> ```Cairo
> 
>     match arr.pop_front() {
>         Option::Some(index_value) => {
> ```





_Suggestion:_
```Cairo
array_value
```
___
*[`listings/ch06-enums-and-pattern-matching/no_listing_03_enum_option/src/lib.cairo` line 9 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/589#-NqTv1QHDi6SLU5l2t57:-NqTv1QHDi6SLU5l2t58:b45h) ([raw file](https://github.com/cairo-book/cairo-book/blob/bb2551a613764ae928ccc40417fd1003b03738de/listings/ch06-enums-and-pattern-matching/no_listing_03_enum_option/src/lib.cairo#L9)):*
> ```Cairo
>                 found = Option::Some(index)
>             } else {
>                 find_value_recursive(arr, value, index + 1);
> ```


___
*[`listings/ch06-enums-and-pattern-matching/no_listing_03_enum_option/src/lib.cairo` line 23 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/589#-NqTxnYmElzcBzcN7D2k:-NqTxnYmElzcBzcN7D2l:bsuswy1) ([raw file](https://github.com/cairo-book/cairo-book/blob/bb2551a613764ae928ccc40417fd1003b03738de/listings/ch06-enums-and-pattern-matching/no_listing_03_enum_option/src/lib.cairo#L23)):*
> ```Cairo
>     let mut found: Option<usize> = Option::None;
> 
>     while index < length {
> ```

lets go back to loop{}. We can't use `break` inside `while` (yet), that's sad :(

**Review by enitrat — COMMENTED** [review]
and the last one:
```rust
// using array indexes and loop

fn loop3(arr: Span<u8>, value: u8) -> Option<usize> {
    let mut index = 0;
    loop {
        if arr.len() == index {
            break Option::None;
        }

        if *arr[index] == value {
            break Option::Some(index);
        }

        index += 1;
    }
}


    #[test]
    // 569730
    fn test_loop3() {
        let arr = array![1, 2, 3, 4, 5].span();
        assert_eq!(super::loop3(arr, 3), Option::Some(2));
    }
}
```

> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/589#-:-NqTyD3u4b7-sNxPsn0r:bt08l62)* status: all files reviewed, 3 unresolved discussions (waiting on @TAdev0)

**Review by TAdev0 — COMMENTED** [review]
nice! thanks

> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/589#-:-NqU3zLzCjT2oLXupXt6:b-w3vddi)* status: all files reviewed, 3 unresolved discussions (waiting on @enitrat)

___
*[`listings/ch06-enums-and-pattern-matching/no_listing_03_enum_option/src/lib.cairo` line 5 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/589#-NqTv6hlBdR12UNPowDE:-NqU3uNTAxmmLum6ijSq:b-yigp24) ([raw file](https://github.com/cairo-book/cairo-book/blob/bb2551a613764ae928ccc40417fd1003b03738de/listings/ch06-enums-and-pattern-matching/no_listing_03_enum_option/src/lib.cairo#L5)):*
> ```Cairo
> 
>     match arr.pop_front() {
>         Option::Some(index_value) => {
> ```

corrected
___
*[`listings/ch06-enums-and-pattern-matching/no_listing_03_enum_option/src/lib.cairo` line 23 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/589#-NqTxnYmElzcBzcN7D2k:-NqU3b71-YQCNAtwX-L1:b852lc7) ([raw file](https://github.com/cairo-book/cairo-book/blob/bb2551a613764ae928ccc40417fd1003b03738de/listings/ch06-enums-and-pattern-matching/no_listing_03_enum_option/src/lib.cairo#L23)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

lets go back to loop{}. We can't use `break` inside `while` (yet), that's sad :(
</blockquote></details>

we dont need to , to make it work. but yeah your benchmark showed loop{] will use less gas

**Review by enitrat — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/589)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TAdev0)

**Pull request merged**
