### PR TITLE
ch11 add serialization explanation and minor additions

### PR DESCRIPTION
**Pull request by kwkr**
Fix some issues mentioned in #568

- - -
This change is [Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/644)

### CODE REVIEW

**Comment by TAdev0** [comment]
@kwkr  thanks for the add of HashStateExTrait !

I'm not sure that the wikipedia link is accurate pour serialization. @enitrat  What do you think of adding a short explanation of what serialization is here?

**Review by enitrat — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/644)* status: all files reviewed, 1 unresolved discussion (waiting on @kwkr)

___
*[`src/ch11-05-hash.md` line 49 at r1](https://reviewable.io/reviews/cairo-book/cairo-book/644#-NrtCxNHAIGxZI5uYBFT:-NrtCxNHAIGxZI5uYBFU:b-4pbdi2) ([raw file](https://github.com/cairo-book/cairo-book/blob/bf9dedfabc61077f88ecef5ea83716e36ca1ef8f/src/ch11-05-hash.md#L49)):*
> ```Markdown
> Pedersen is different from Poseidon, as it starts with a base state. This base state must be of `felt252` type, which forces us to either hash the struct with an arbitrary base state using the `update_with` method, or serialize the struct into an array to loop through all of its fields and hash its elements together. 
> 
> > **[Serialization](https://en.wikipedia.org/wiki/Serialization)** is a process of transforming data structures into a format that can be easily stored or transmitted. Let's say you are running a program and would like to persist its state to be able to resume it later. To do this, you could take each of the objects your program is using and save information about them, for example in a file. This exactly is a simplified version of serialization. Now if you want to resume your program with this saved state, you would perform **deserialization** which means you would load the state of the objects from some source.
> ```

i think this would be better here https://book.cairo-lang.org/appendix-03-derivable-traits.html?highlight=serialize#serializing-with-serde

**Comment by kwkr** [comment]
@enitrat I moved the serialization note.

**Review by enitrat — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/644)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kwkr)

**Pull request merged**
