### PR TITLE
System Calls chapter

### LINKED ISSUE #269: feat: syscalls
List the syscalls available on Starknet, what they do, and how to call them. You will write explanatory text for each syscall and provide a **meaningful** example
This will be an appendix.
est. 1 hour

### PR DESCRIPTION
**Pull request by julienbrs**
closes #269

Replicated the Starknet Docs page about System Calls as discussed in https://github.com/cairo-book/cairo-book/issues/269.

Added a table of contents for better readability. Please let me know if it's okay.

- - -
This change is [Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/511)

### CODE REVIEW

**Comment by enitrat** [comment]
ah, I did not know that it was now in the Starknet documentation... At the time the issue was open, there was no such thing so it made sense to have it in the book. Now, I'm not so sure anymore.

Anyway, I think we can have it in the appendix for now but it might be removed in the future if judged no longer relevant

**Comment by julienbrs** [comment]
> ah, I did not know that it was now in the Starknet documentation... At the time the issue was created, there was no such thing so it made sense to have it in the book. Now, I'm not so sure anymore.
> 
> Anyway, I think we can have it in the appendix for now but it might be removed in the future if judged no longer relevant

There was already a discussion about that here https://github.com/cairo-book/cairo-book/issues/269#issuecomment-1733132368 if you can give it a look please

**Comment by enitrat** [comment]
> > ah, I did not know that it was now in the Starknet documentation... At the time the issue was created, there was no such thing so it made sense to have it in the book. Now, I'm not so sure anymore.
> > Anyway, I think we can have it in the appendix for now but it might be removed in the future if judged no longer relevant
> 
> There was already a discussion about that here [#269 (comment)](https://github.com/cairo-book/cairo-book/issues/269#issuecomment-1733132368) if you can give it a look please

ah yeah indeed 🤦 
ok, let's have it but in the appendix then !

**Comment by julienbrs** [comment]
I moved it to appendix as the last chapter, but maybe it would be better to have it after the `Derivable Traits` chapter? It makes more sense to me

**Review by enitrat — APPROVED** [review]

**Comment by enitrat** [comment]
I think it's fine to have it here for now

**Pull request merged**
