### PR TITLE
Maintain:  smart contracts chapters

### LINKED ISSUE #345: Add standalone contract public functions description
```rust
#[external(v0)]
fn my_function(ref self: ContractState){}
```

Public functions are not necessarily under impls blocks.

### PR DESCRIPTION
**Pull request by TAdev0**
Resolves #345

- - -
This change is [Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/645)

### CODE REVIEW

**Comment by TAdev0** [comment]
@enitrat  work in progress
for now, I:
- modified the modulo of pedersen hash in the storage layout as it was incorrect ( 2^251 - 256 instead of P )
- added a small intro to starknet foundry avec scarb description for environments for cairo contracts development
- added standalone public functions description (but maybe you want to add details related to components?)
-

**Comment by enitrat** [comment]
@TAdev0 Perhaps it's best to start thinking about the refactoring of this second section. We can for sure keep some well written and accurate isolated sections (contract storage, storage costs, etc) but overall we should think of a new organization, with clearer examples, more accurate information, delivered in the right order.

**Review by enitrat — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/645)* status: all files reviewed, 4 unresolved discussions (waiting on @TAdev0)

___
*[`src/ch12-01-general-introduction-to-smart-contracts.md` line 48 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/645#-NrvI0Y90vhOEhRRnOiS:-NrvI0Y90vhOEhRRnOiT:b-z7k69o) ([raw file](https://github.com/cairo-book/cairo-book/blob/0991ee67938b2f4c5a7c910951ab135249979d74/src/ch12-01-general-introduction-to-smart-contracts.md#L48)):*
> ```Markdown
> Ethereum, being the most widely used and resilient smart contract platform, became a victim of its own success. With the rapid adoption of some previously mentioned use cases, mainly DeFi, the cost of performing transactions became extremely high, rendering the network almost unusable. Engineers and researchers in the ecosystem began working on solutions to address this scalability issue.
> 
> A famous trilemma called The Blockchain Trilemma in the blockchain space states that it is impossible to achieve a high level of scalability, decentralization, and security simultaneously; trade-offs must be made. Ethereum is at the intersection of decentralization and security. Eventually, it was decided that Ethereum's purpose would be to serve as a secure settlement layer, while complex computations would be offloaded to other networks built on top of Ethereum. These are called Layer 2s (L2s).
> ```

we should keep the link
___
*[`src/ch13-01-contract-storage.md` line 21 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/645#-NrvIQ-c2HhSoxFniQ_G:-NrvIQ-c2HhSoxFniQ_H:bfn8qmw) ([raw file](https://github.com/cairo-book/cairo-book/blob/0991ee67938b2f4c5a7c910951ab135249979d74/src/ch13-01-contract-storage.md#L21)):*
> ```Markdown
> 
> - If the variable is a single value (not a mapping), the address is the `sn_keccak` hash of the ASCII encoding of the variable's name. `sn_keccak` is Starknet's version of the Keccak256 hash function, whose output is truncated to 250 bits.
> - If the variable is a [mapping](./ch13-01-contract-storage.html#storage-mappings) with a key `k`, the address of the value at key `k` is `h(sn_keccak(variable_name),k)`, where ℎ is the Pedersen hash and the final value is taken modulo \\( {2^{251}} + 17 \cdot {2^{192}} + 1 \\). If the key is composed of more than one `felt252`, the address of the value will be `h(...h(h(sn_keccak(variable_name),k_1),k_2),...,k_n)`, with `k_1,...,k_n` being all `felt252` that constitute the key.
> ```

are you sure?



_Code quote:_
```Markdown
and the final value is taken modulo \\( {2^{251}} + 17 \cdot {2^{192}} + 1 \\)
```
___
*[`src/ch13-01-contract-storage.md` line 76 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/645#-NrvIZgxBeS37wi9XFMQ:-NrvIZgxBeS37wi9XFMR:b-pin9wn) ([raw file](https://github.com/cairo-book/cairo-book/blob/0991ee67938b2f4c5a7c910951ab135249979d74/src/ch13-01-contract-storage.md#L76)):*
> ```Markdown
> ```
> 
> Note that we also need to derive `Drop` and `Serde` traits to properly use custom types in contracts storage.
> ```

serde is for entrypoints and drop is not inherent to. storage i think we can remove
___
*[`src/ch13-01-contract-storage.md` line 130 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/645#-NrvIqiTDh-uHW7EbpHg:-NrvIqiTDh-uHW7EbpHh:b-3lvvrv) ([raw file](https://github.com/cairo-book/cairo-book/blob/0991ee67938b2f4c5a7c910951ab135249979d74/src/ch13-01-contract-storage.md#L130)):*
> ```Markdown
> 
> The address in storage of a variable stored in a mapping is computed according to the description in the [Storage Addresses](#storage-addresses) section.
> If the key of a mapping is a struct, each element of the struct constitutes a key. Moreover, the struct should implement the `Hash` trait, which can be derived with the `#[derive(Hash)]` attribute. For example, if you have a struct with two fields, the address will be `h(h(sn_keccak(variable_name),k_1),k_2)` modulo \\( {2^{251}} + 17 \cdot {2^{192}} + 1 \\), where `k_1` and `k_2` are the values of the two fields of the struct.
> ```

same where i s this from?



_Code quote:_
```Markdown
 modulo \\( {2^{251}} + 17 \cdot {2^{192}} + 1 \\)
```

**Review by TAdev0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/645)* status: all files reviewed, 4 unresolved discussions (waiting on @enitrat)

___
*[`src/ch13-01-contract-storage.md` line 76 at r2](https://reviewable.io/reviews/cairo-book/cairo-book/645#-NrvIZgxBeS37wi9XFMQ:-NrvMMa-BxH4NkKFwwrA:bb7f2mf) ([raw file](https://github.com/cairo-book/cairo-book/blob/0991ee67938b2f4c5a7c910951ab135249979d74/src/ch13-01-contract-storage.md#L76)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

serde is for entrypoints and drop is not inherent to. storage i think we can remove
</blockquote></details>

done

**Review by enitrat — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/645#-:-NrvomZL3QH3SqrgJ7rX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TAdev0)

**Pull request merged**
