### PR TITLE
simplify explanation in src/ch03-01-arrays.md

### PR DESCRIPTION
**Pull request by kwkr**
This change is [Reviewable](https://reviewable.io/reviews/cairo-book/cairo-book/601)

### CODE REVIEW

**Comment by enitrat** [comment]
@kwkr please open one PR for all typo fixes

**Comment by enitrat** [comment]
hi @kwkr thanks for your dedication, please make it easy for reviews and avoid spamming PRs.

**Comment by kwkr** [comment]
@enitrat Sorry for that. I didn't see your comment early enough. I thought it would be easier to review since each PR is regarding a specific page. This way if some changes are rejected, the process will be much easier. Nevertheless, if you want, I can merge all of this into one PR.

**Comment by enitrat** [comment]
@kwkr if it's not too hard, please do - as it easier to read everything in one go than to cycle through 20 prs, follow the feedbacks, approve & merge etc

**Comment by kwkr** [comment]
@enitrat I will take care of that.

**Comment by enitrat** [comment]
thank you!

**Comment by kwkr** [comment]
@enitrat see #618

**Pull request closed without merging**
